name = "hackathon-landing-page"
compatibility_date = "2025-08-28"
pages_build_output_dir = "./dist"

[assets]
directory = "./dist/"
not_found_handling = "404-page"

[vars]
TURSO_DATABASE_URL=""
TURSO_AUTH_TOKEN=""