name = "hackathon-landing-page"
compatibility_date = "2025-08-28"

[assets]
directory = "./dist/"
not_found_handling = "404-page"

[vars]
TURSO_DATABASE_URL=""
TURSO_AUTH_TOKEN=""
CLODUFLARE_TURNSTILE_SECRET=""
AWS_REGION=""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""